name: certbot-dns-loopia
summary: Loopia DNS authentication plugin for Certbot
description: Loopia DNS authentication plugin for Certbot
confinement: strict
grade: stable
base: core20

adopt-info: certbot-dns-loopia

parts:
  certbot-dns-loopia:
    plugin: python
    source: .
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version `grep ^version $SNAPCRAFT_PART_SRC/setup.py | cut -f2 -d= | tr -d "'[:space:]"`
    build-environment:
      - SNAP_BUILD: "True"
    
  certbot-metadata:
    plugin: dump
    source: .
    stage: [setup.py, certbot-shared]
    override-pull: |
        snapcraftctl pull
        mkdir -p $SNAPCRAFT_PART_SRC/certbot-shared
    
slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.8/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
